### PR TITLE
Show turret health circle

### PR DESCRIPTION
**Pull request by LT71**

### CODE REVIEW

**Comment by steam-test1** [comment]
If the health changes when the host damages a swat turret, then the check can be removed

**Comment by LT71** [comment]
Okay so right now if the host hits the turret the damage bar wont show that? And that is why  the check is there?

**Comment by steam-test1** [comment]
It needs testing
If you remove the check and check if the damage changes updates when the host damages the swat turret

**Comment by LT71** [comment]
I tested this with both the circle and health bar and it did show the damage the host did as far as I could tell

**Pull request merged**
